# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1097ccbfbf1bb06cd467f2549f8db79089846000eee729087c70449120a7ea9258cf8fd24abfb3641fa32a0614d86701dc951194565d03372b6e15619c77c7d0

test:
  secret_key_base: 19a99d059af46ae43c68adcbf735a613c224873c9b9c2bbc85a692f5d13988d16078068fa9803751371b1086a9055221bf017e9028be0c3bf5a779d6f5077a6a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
